# Generated by Django 3.1.7 on 2021-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DynamicId', models.CharField(max_length=10000)),
                ('CollectorsOpenid', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerImage', models.CharField(max_length=10000)),
                ('reviewerOpenid', models.CharField(max_length=10000)),
                ('reviewerContent', models.CharField(max_length=10000)),
                ('reviewerName', models.CharField(max_length=10000)),
                ('commentId', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentImg', models.CharField(blank=True, max_length=100000)),
                ('contentText', models.CharField(blank=True, max_length=10000)),
                ('contentPublisherOpenid', models.CharField(blank=True, max_length=100000)),
                ('publisherName', models.CharField(blank=True, max_length=100)),
                ('publisherProfile', models.CharField(blank=True, max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeContentId', models.CharField(max_length=10000)),
                ('likerOpenid', models.CharField(max_length=100000)),
                ('likeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('avatarUrl', models.CharField(max_length=10000)),
                ('openid', models.CharField(max_length=10000)),
            ],
        ),
    ]
